### ISSUE TITLE
GitDsc/GitClone with option to name destination folder

### ISSUE THREAD

**Issue by FlippingBinary** [microsoft/winget-dsc#202]
### Description of the new feature / enhancement

I use a repository to track changes to my NeoVim configuration and clone it locally to the location where NeoVim expects to find it. `GitDsc/GitClone` gets me halfway there, but the name of the repository doesn't match the name the folder needs to be for NeoVim to pick it up. Since `GitDsc/GitClone` works by changing the working directory to the `RootDirectory`, then cloning with the equivalent of `git clone <remote>` rather than `git clone <remote> <destination>`, making my DSC idempotent is much more complicated than it would be if I could override the destination.

### Proposed technical implementation details

Git will create parent directories as needed to clone to a named destination folder, so `GitDsc/GitClone` could take an additional parameter (e.g. `RootName`) to use in the call to git, if it is provided.

For example, it could be used in DSCv3 like this:

```
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
- name: Use PowerShell resources
  type: Microsoft.DSC/PowerShell
  properties:
    resources:
    - name: Clone NeoVim configuration
      type: GitDsc/GitClone
      properties:
        HttpsUrl: "https://github.com/FlippingBinary/nvim-config.git"
        RootDirectory: "[envvar('LOCALAPPDATA')]"
        RootName: "nvim"
```

The resulting call to git would be `git clone https://github.com/FlippingBinary/nvim-config.git nvim`, executed from the local AppData directory. Without the `RootName` parameter, it could simply omit the destination in its call to `git`, just like it does currently. This would provide backward compatibility with existing uses.
