### ISSUE TITLE
Microsoft.Windows.Settings SystemColorMode isn't applied on external monitors

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-dsc#206]
### Brief description of your issue

When I run the following configuration resulting in a change to my SystemColorMode, my main display gets updated, but external displays do not.
 
```yaml
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json
metadata:
  winget:
    processor: dscv3
resources:
  - name: WindowsSettings
    type: Microsoft.Windows.Settings/WindowsSettings
    metadata:
      allowPrerelease: true
      description: Configure Windows Settings
      securityContext: elevated
    properties:
      AppColorMode: Dark
      DeveloperMode: true
      SystemColorMode: Dark
      TaskbarAlignment: Left
```

### Steps to reproduce

Run a WinGet Configuration using the above sample on a device in "Light Mode".

### Expected behavior

All displays get updated the same way they do when I select the option in Windows Settings.

### Actual behavior

The main monitor gets updated, but the external displays do not.

### Environment

```shell
winget --info
    Windows Package Manager (Preview) v1.11.320-preview
    Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26100.3983
System Architecture: Arm64
Package: Microsoft.DesktopAppInstaller v1.26.320.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads
Configuration Modules              %LOCALAPPDATA%\Microsoft\WinGet\Configuration\Modules

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```
