### ISSUE TITLE
dotnet dsc resource only works on second run

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/winget-dsc#83]
### Brief description of your issue

I have to run the configuration file twice for it to work, always fails on first run 

Using Microsoft.DotNet.DSC/DotNetToolPackage

### Steps to reproduce

1. Run this config file [GlobalTool-TEST.zip](https://github.com/user-attachments/files/17547174/GlobalTool-TEST.zip)

### Expected behavior

For it to work on first run

### Actual behavior

Only works on second try

### Environment

Windows: Windows.Desktop v10.0.26100.2033
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled

**Comment by denelon** [comment]
First Run:

![Image](https://github.com/user-attachments/assets/7348f03d-19bc-48e0-9c1a-e6ff13711836)

Second Run:

![Image](https://github.com/user-attachments/assets/06f37b86-0afa-4fa1-8805-dcae8e4412f6)

**Comment by denelon** [comment]
```YAML
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: install-dotnet9-SDK
      directives:
        description: Install .NET 9 SDK
        securityContext: elevated
      settings:
        id: Microsoft.DotNet.SDK.9
        source: winget
    - resource: Microsoft.DotNet.DSC/DotNetToolPackage
      dependsOn:
        - install-dotnet9-SDK
      directives:
        description: Install Microsoft.dotnet-scaffold
        allowPrerelease: true
      settings:
        PackageId: microsoft.dotnet-scaffold
        Version: 9.0.1
        Prerelease: true
        Exist: true
    - resource: Microsoft.DotNet.DSC/DotNetToolPackage
      dependsOn:
          - install-dotnet9-SDK
      directives:
        description: Install Microsoft.dotnet-scaffold-aspire
        allowPrerelease: true
      settings:
        PackageId: microsoft.dotnet-scaffold-aspire
        Version: 9.0.1
        Prerelease: true
        Exist: true
    - resource: Microsoft.DotNet.DSC/DotNetToolPackage
      dependsOn:
        - install-dotnet9-SDK
      directives:
        description: Install Microsoft.dotnet-scaffold-aspnet
        allowPrerelease: true
      settings:
        PackageId: microsoft.dotnet-scaffold-aspnet
        Version: 9.0.1
        Prerelease: true
        Exist: true
  configurationVersion: 0.2.0
```
